package com.example.naturalfisherapp.utilidades;

public enum EnumVariables {

    /**
     * Variables Configuracion
     */

    /*VARIABLES MODOS*/
    MODO_CREACION("MODO_CREACION"),
    MODO_CONSULTA("MODO_CONSULTA"),
    MODO_EDICION("MODO_EDICION"),
    /*TIPOS DE INPUTS*/
    NUMBER("NUMBER"),
    LETRAS("LETRAS"),
    /*VARIABLES CONFIGURACION*/
    DIRECCION_IP_SERVIDOR("DIRECCION_IP_SERVIDOR"),
    PUERTO_SERVIDOR("PUERTO_SERVIDOR"),
    /*FRAGMENTS*/
    FRAGMENT_PROMOCION_DETALLE("FRAGMENT_PROMOCION_DETALLE"),
    FRAGMENT_PRODUCTO_BUSQUEDA("FRAGMENT_PRODUCTO_BUSQUEDA"),
    FRAGMENT_VENTA_BUSQUEDA("FRAGMENT_VENTA_BUSQUEDA"),
    FRAGMENT_DETALLE_REGISTRO_VENTA("FRAGMENT_DETALLE_REGISTRO_VENTA"),
    FRAGMENT_ESTADISTICA_PRODUCTO_BUSQUEDA("FRAGMENT_ESTADISTICA_PRODUCTO_BUSQUEDA"),
    FRAGMENT_INVERSION_BUSQUEDA("FRAGMENT_INVERSION_BUSQUEDA"),
    FRAGMENT_DETALLE_INVERSION("FRAGMENT_DETALLE_INVERSION");

    private final String valor;

    EnumVariables(String pCodigo){
        this.valor = pCodigo;
    }

    public String getValor(){
        return valor;
    }
}
